# Site configuration
domain: "http://shellteo.top"
baseurl: ""
url: "http://shellteo.github.io/"
permalink: /:title/
avatar: https://i.loli.net/2018/08/03/5b632b480377a.jpg
about: https://i.loli.net/2018/08/03/5b632b480377a.jpg
favicon: http://pbwv866yd.bkt.clouddn.com/favicon.ico
basecss: 
# Theme specific configuration
title: shellteo
description: >
  Hi there, My name is Luozhan.Song, usually I use "songroger" as my ID everywhere.
  I was born and raised in Hunan China. 
  I'm really fond of beautiful design, drawing etc.

# Contact and social media links
github_username: shellteo
weibo_username: ZxPlus

exclude: ['node_modules', 'gulpfile.js', 'package.json']

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account
# before deploy your webpage
enable_comment: false
# disqus_account: songroger

gems: ['jekyll-paginate']
# Pagination
paginate: 5
paginate_path: /page:num
